### ISSUE TITLE
Polish example module

### ISSUE THREAD

**Issue by tauno** [thinkshout/migrate_google_sheets#1]
- [x] Change migration name and group names from 'test' to 'migrate_google_sheets_test' or something more specific like that.
- [x] Update uninstall hook to reflect the new name AND remove the group as well.
- [x] Create a dummy example spreadsheet and use that as the source.
- [x] Quick review of other migrate example modules for any additional cleanup we should be doing.

**Comment by mariacha** [comment]
Done
